#!/usr/bin/perl

use 5.022;
use warnings;

use FindBin qw($Bin);
use lib "$Bin/lib";

use Hacker;

my $usage = "Usage:\n\t$0 [--driver=...] [--help] [--play] [--output|-o=file.pcm] [--exec|-e=code] project-file.hacker";
my %args = process_command_line(qw/driver=s play render=s e|exec=s h|help/, $usage);

my @signal;

my $hacker = new Hacker(driver => $args{driver});

if (my $code = $args{exec}) {
	my $code = q[use Hacker;] . $code;
	# Execute
	@signal = eval $code; die $@ if $@;
} else {
	my $file = pop @ARGV or die $usage;
	die "No project file $file" unless -f $file;
	
	@signal = load($file);
}

if (my $file = $args{output}) {
	$hacker->render($file => @signal);
	exit;
}

$hacker->play(@signal);

1;
