#!/usr/bin/perl

use 5.022;
use warnings;

use FindBin qw($Bin);
use lib "$Bin/lib";

use Hacker;

my $usage = "Usage:\n\t$0 [--driver=...] [--help] [--play] [--output|-o=file.pcm] [--exec|-e=code] [project-file.hacker] [-]";
my %args = process_command_line(qw/driver=s play o|output=s e|exec=s h|help/, $usage);

my @signal;

my $hacker = new Hacker(driver => $args{driver});

my $console = $ARGV[-1] // '' eq '-';

my $file = $ARGV[-1] // '';

if (my $code = $args{exec} || !(-f $file)) {
	if (!$code || $code eq '1') {
		$code = join '', <>;
	}
	
	$code = q[use Hacker;] . $code;
		
	# Execute
	@signal = eval $code; die $@ if $@;
} else {
	my $file = pop @ARGV;
	@signal = load($file);
}

if (my $file = $args{output}) {
	$hacker->render($file => @signal);
} elsif ($console) {
	$hacker->render('<STDOUT>' => @signal);
} else {
	$hacker->play(@signal);
}

1;
